on:
  push: 
    branches:
      - master
jobs:
  build:
    runs-on: ubtuntu-latest
    steps:
      - name: 'Testing Github action'
        run: pwd
      - name: 'Testing Printing'
        run: echo "ASMAA ESMAIL"
      
